nodeLinker: node-modules

plugins:
  - checksum: 3f8b37d3d46cdba0e175b89a3b5c9de40b60da0e2071e0b44b65a6312c3bd4e516cef8cf97ef66ca354eee0350185270e4156c48dc7c00d7248f5d7d3dd29719
    path: .yarn/plugins/@yarnpkg/plugin-script-daemon.cjs
    spec: "https://raw.githubusercontent.com/zwade/yarn-plugin-script-daemon/master/bundles/%40yarnpkg/plugin-script-daemon.js"
  - path: .yarn/plugins/@yarnpkg/plugin-fetch.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.8.2.cjs
